### ISSUE TITLE
Grafic1 este destul de lent

### ISSUE THREAD

**Issue by Tedyst** [Tedyst/Tracker#29]
Pot sa ma uit sau te uiti tu ? @RedPipper

**Comment by RedPipper** [comment]
Am sa ma uit eu can construiesc toata pagina de profile

**Comment by Tedyst** [comment]
De fapt l-am cam reparat eu cand am mutat grafic1 in stats :)))
Am incarcat doar ultimele 4 luni de probleme pentru a face statistici si s-a redus masiv timpul

**Comment by Tedyst** [comment]
Am adaugat cache deci nu ar mai trebui sa fie vreo problema.
