### ISSUE TITLE
Graficele de pe pagina principala

### ISSUE THREAD

**Issue by Tedyst** [Tedyst/Tracker#6]
Are cineva idee ce am putea pune pe graficele acelea ? Sau alte idei de grafice ?

**Comment by RedPipper** [comment]
Deci ideea mea era sa facem un grafic in care sa arate nr de submisii / problema pana ai rezolvat problema

**Comment by RedPipper** [comment]
Si sa luam in considerare ultimele 20 de probleme sau cv gen
